#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

// Empty Item Slots: 102, 120, 242 to 253, 267, 389 and 390.

#define ITEM_NONE                    0

// Balls
#define ITEM_MASTER_BALL             1
#define ITEM_ULTRA_BALL              2
#define ITEM_GREAT_BALL              3
#define ITEM_POKE_BALL               4
#define ITEM_SAFARI_BALL             5
#define ITEM_NET_BALL                6
#define ITEM_DIVE_BALL               7
#define ITEM_NEST_BALL               8
#define ITEM_REPEAT_BALL             9
#define ITEM_TIMER_BALL             10
#define ITEM_LUXURY_BALL            11
#define ITEM_PREMIER_BALL           12

// Pokemon Items
#define ITEM_POTION                 13
#define ITEM_ANTIDOTE               14
#define ITEM_BURN_HEAL              15
#define ITEM_ICE_HEAL               16
#define ITEM_AWAKENING              17
#define ITEM_PARALYZE_HEAL          18
#define ITEM_FULL_RESTORE           19
#define ITEM_MAX_POTION             20
#define ITEM_HYPER_POTION           21
#define ITEM_SUPER_POTION           22
#define ITEM_FULL_HEAL              23
#define ITEM_REVIVE                 24
#define ITEM_MAX_REVIVE             25
#define ITEM_FRESH_WATER            26
#define ITEM_SODA_POP               27
#define ITEM_LEMONADE               28
#define ITEM_MOOMOO_MILK            29
#define ITEM_ENERGY_POWDER          30
#define ITEM_ENERGY_ROOT            31
#define ITEM_HEAL_POWDER            32
#define ITEM_REVIVAL_HERB           33
#define ITEM_ETHER                  34
#define ITEM_MAX_ETHER              35
#define ITEM_ELIXIR                 36
#define ITEM_MAX_ELIXIR             37
#define ITEM_LAVA_COOKIE            38
#define ITEM_BLUE_FLUTE             39
#define ITEM_YELLOW_FLUTE           40
#define ITEM_RED_FLUTE              41
#define ITEM_BLACK_FLUTE            42
#define ITEM_WHITE_FLUTE            43
#define ITEM_BERRY_JUICE            44
#define ITEM_SACRED_ASH             45
#define ITEM_SHOAL_SALT             46
#define ITEM_SHOAL_SHELL            47
#define ITEM_RED_SHARD              48
#define ITEM_BLUE_SHARD             49
#define ITEM_YELLOW_SHARD           50
#define ITEM_GREEN_SHARD            51
#define ITEM_MUSCLE_BAND            52
#define ITEM_WISE_GLASSES           53
#define ITEM_EXPERT_BELT            54
#define ITEM_FOCUS_SASH             55
#define ITEM_FULL_INCENSE           56
#define ITEM_LUCK_INCENSE           57
#define ITEM_ODD_INCENSE            58
#define ITEM_PURE_INCENSE           59
#define ITEM_ROCK_INCENSE           60
#define ITEM_ROSE_INCENSE           61
#define ITEM_WAVE_INCENSE           62
#define ITEM_HP_UP                  63
#define ITEM_PROTEIN                64
#define ITEM_IRON                   65
#define ITEM_CARBOS                 66
#define ITEM_CALCIUM                67
#define ITEM_RARE_CANDY             68
#define ITEM_PP_UP                  69
#define ITEM_ZINC                   70
#define ITEM_PP_MAX                 71
#define ITEM_LAGGING_TAIL           72
#define ITEM_GUARD_SPEC             73
#define ITEM_DIRE_HIT               74
#define ITEM_X_ATTACK               75
#define ITEM_X_DEFEND               76
#define ITEM_X_SPEED                77
#define ITEM_X_ACCURACY             78
#define ITEM_X_SPECIAL              79
#define ITEM_POKE_DOLL              80
#define ITEM_FLUFFY_TAIL            81
#define ITEM_BIG_ROOT               82
#define ITEM_SUPER_REPEL            83
#define ITEM_MAX_REPEL              84
#define ITEM_ESCAPE_ROPE            85
#define ITEM_REPEL                  86
#define ITEM_POWER_WEIGHT           87
#define ITEM_POWER_BRACER           88
#define ITEM_POWER_BELT             89
#define ITEM_POWER_ANKLET           90
#define ITEM_POWER_LENS             91
#define ITEM_POWER_BAND             92
#define ITEM_SUN_STONE              93
#define ITEM_MOON_STONE             94
#define ITEM_FIRE_STONE             95
#define ITEM_THUNDER_STONE          96
#define ITEM_WATER_STONE            97
#define ITEM_LEAF_STONE             98
#define ITEM_DAWN_STONE             99
#define ITEM_DUSK_STONE            100
#define ITEM_SHINY_STONE           101
#define ITEM_066                   102
#define ITEM_TINY_MUSHROOM         103
#define ITEM_BIG_MUSHROOM          104
#define ITEM_HONEY                 105
#define ITEM_PEARL                 106
#define ITEM_BIG_PEARL             107
#define ITEM_STARDUST              108
#define ITEM_STAR_PIECE            109
#define ITEM_NUGGET                110
#define ITEM_HEART_SCALE           111
#define ITEM_DUBIOUS_DISC          112
#define ITEM_ELECTIRIZER           113
#define ITEM_MAGMARIZER            114
#define ITEM_OVAL_STONE            115
#define ITEM_PROTECTOR             116
#define ITEM_RAZOR_CLAW            117
#define ITEM_RAZOR_FANG            118
#define ITEM_REAPER_CLOTH          119
#define ITEM_078                   120
#define ITEM_ORANGE_MAIL           121
#define ITEM_HARBOR_MAIL           122
#define ITEM_GLITTER_MAIL          123
#define ITEM_MECH_MAIL             124
#define ITEM_WOOD_MAIL             125
#define ITEM_WAVE_MAIL             126
#define ITEM_BEAD_MAIL             127
#define ITEM_SHADOW_MAIL           128
#define ITEM_TROPIC_MAIL           129
#define ITEM_DREAM_MAIL            130
#define ITEM_FAB_MAIL              131
#define ITEM_RETRO_MAIL            132
#define ITEM_CHERI_BERRY           133
#define ITEM_CHESTO_BERRY          134
#define ITEM_PECHA_BERRY           135
#define ITEM_RAWST_BERRY           136
#define ITEM_ASPEAR_BERRY          137
#define ITEM_LEPPA_BERRY           138
#define ITEM_ORAN_BERRY            139
#define ITEM_PERSIM_BERRY          140
#define ITEM_LUM_BERRY             141
#define ITEM_SITRUS_BERRY          142
#define ITEM_FIGY_BERRY            143
#define ITEM_WIKI_BERRY            144
#define ITEM_MAGO_BERRY            145
#define ITEM_AGUAV_BERRY           146
#define ITEM_IAPAPA_BERRY          147
#define ITEM_RAZZ_BERRY            148
#define ITEM_BLUK_BERRY            149
#define ITEM_NANAB_BERRY           150
#define ITEM_WEPEAR_BERRY          151
#define ITEM_PINAP_BERRY           152
#define ITEM_POMEG_BERRY           153
#define ITEM_KELPSY_BERRY          154
#define ITEM_QUALOT_BERRY          155
#define ITEM_HONDEW_BERRY          156
#define ITEM_GREPA_BERRY           157
#define ITEM_TAMATO_BERRY          158
#define ITEM_CORNN_BERRY           159
#define ITEM_MAGOST_BERRY          160
#define ITEM_RABUTA_BERRY          161
#define ITEM_NOMEL_BERRY           162
#define ITEM_SPELON_BERRY          163
#define ITEM_PAMTRE_BERRY          164
#define ITEM_WATMEL_BERRY          165
#define ITEM_DURIN_BERRY           166
#define ITEM_BELUE_BERRY           167
#define ITEM_LIECHI_BERRY          168
#define ITEM_GANLON_BERRY          169
#define ITEM_SALAC_BERRY           170
#define ITEM_PETAYA_BERRY          171
#define ITEM_APICOT_BERRY          172
#define ITEM_LANSAT_BERRY          173
#define ITEM_STARF_BERRY           174
#define ITEM_ENIGMA_BERRY          175
#define ITEM_ADAMANT_ORB           176
#define ITEM_LUSTROUS_ORB          177
#define ITEM_GRISEOUS_ORB          178

// hold items
#define ITEM_BRIGHT_POWDER         179
#define ITEM_WHITE_HERB            180
#define ITEM_MACHO_BRACE           181
#define ITEM_EXP_SHARE             182
#define ITEM_QUICK_CLAW            183
#define ITEM_SOOTHE_BELL           184
#define ITEM_MENTAL_HERB           185
#define ITEM_CHOICE_BAND           186
#define ITEM_KINGS_ROCK            187
#define ITEM_SILVER_POWDER         188
#define ITEM_AMULET_COIN           189
#define ITEM_CLEANSE_TAG           190
#define ITEM_SOUL_DEW              191
#define ITEM_DEEP_SEA_TOOTH        192
#define ITEM_DEEP_SEA_SCALE        193
#define ITEM_SMOKE_BALL            194
#define ITEM_EVERSTONE             195
#define ITEM_FOCUS_BAND            196
#define ITEM_LUCKY_EGG             197
#define ITEM_SCOPE_LENS            198
#define ITEM_METAL_COAT            199
#define ITEM_LEFTOVERS             200
#define ITEM_DRAGON_SCALE          201
#define ITEM_LIGHT_BALL            202
#define ITEM_SOFT_SAND             203
#define ITEM_HARD_STONE            204
#define ITEM_MIRACLE_SEED          205
#define ITEM_BLACK_GLASSES         206
#define ITEM_BLACK_BELT            207
#define ITEM_MAGNET                208
#define ITEM_MYSTIC_WATER          209
#define ITEM_SHARP_BEAK            210
#define ITEM_POISON_BARB           211
#define ITEM_NEVER_MELT_ICE        212
#define ITEM_SPELL_TAG             213
#define ITEM_TWISTED_SPOON         214
#define ITEM_CHARCOAL              215
#define ITEM_DRAGON_FANG           216
#define ITEM_SILK_SCARF            217
#define ITEM_UP_GRADE              218
#define ITEM_SHELL_BELL            219
#define ITEM_SEA_INCENSE           220
#define ITEM_LAX_INCENSE           221
#define ITEM_LUCKY_PUNCH           222
#define ITEM_METAL_POWDER          223
#define ITEM_THICK_CLUB            224
#define ITEM_STICK                 225
#define ITEM_DRACO_PLATE           226
#define ITEM_DREAD_PLATE           227
#define ITEM_EARTH_PLATE           228
#define ITEM_FIST_PLATE            229
#define ITEM_FLAME_PLATE           230
#define ITEM_ICICLE_PLATE          231
#define ITEM_INSECT_PLATE          232
#define ITEM_IRON_PLATE            233
#define ITEM_MEADOW_PLATE          234
#define ITEM_MIND_PLATE            235
#define ITEM_SKY_PLATE             236
#define ITEM_SPLASH_PLATE          237
#define ITEM_SPOOKY_PLATE          238
#define ITEM_STONE_PLATE           239
#define ITEM_TOXIC_PLATE           240
#define ITEM_ZAP_PLATE             241
#define ITEM_0F2                   242
#define ITEM_0F3                   243
#define ITEM_0F4                   244
#define ITEM_0F5                   245
#define ITEM_0F6                   246
#define ITEM_0F7                   247
#define ITEM_0F8                   248
#define ITEM_0F9                   249
#define ITEM_0FA                   250
#define ITEM_0FB                   251
#define ITEM_0FC                   252
#define ITEM_0FD                   253
#define ITEM_RED_SCARF             254
#define ITEM_BLUE_SCARF            255
#define ITEM_PINK_SCARF            256
#define ITEM_GREEN_SCARF           257
#define ITEM_YELLOW_SCARF          258

// Key Items
#define ITEM_MACH_BIKE             259 // The Mach Bike is completely useless, as the Acro Bike fulfills both of their purposes.
#define ITEM_COIN_CASE             260
#define ITEM_ITEMFINDER            261
#define ITEM_OLD_ROD               262
#define ITEM_GOOD_ROD              263
#define ITEM_SUPER_ROD             264
#define ITEM_SS_TICKET             265
#define ITEM_CONTEST_PASS          266
#define ITEM_10B                   267
#define ITEM_WAILMER_PAIL          268
#define ITEM_DEVON_GOODS           269
#define ITEM_SOOT_SACK             270
#define ITEM_BASEMENT_KEY          271
#define ITEM_ACRO_BIKE             272
#define ITEM_POKEBLOCK_CASE        273
#define ITEM_LETTER                274
#define ITEM_EON_TICKET            275
#define ITEM_RED_ORB               276
#define ITEM_BLUE_ORB              277
#define ITEM_SCANNER               278
#define ITEM_GO_GOGGLES            279
#define ITEM_METEORITE             280
#define ITEM_ROOM_1_KEY            281
#define ITEM_ROOM_2_KEY            282
#define ITEM_ROOM_4_KEY            283
#define ITEM_ROOM_6_KEY            284
#define ITEM_STORAGE_KEY           285
#define ITEM_ROOT_FOSSIL           286
#define ITEM_CLAW_FOSSIL           287
#define ITEM_DEVON_SCOPE           288

// TMs/HMs
#define ITEM_TM01_FOCUS_PUNCH      289
#define ITEM_TM02_DRAGON_CLAW      290
#define ITEM_TM03_WATER_PULSE      291
#define ITEM_TM04_CALM_MIND        292
#define ITEM_TM05_ROAR             293
#define ITEM_TM06_TOXIC            294
#define ITEM_TM07_HAIL             295
#define ITEM_TM08_BULK_UP          296
#define ITEM_TM09_BULLET_SEED      297
#define ITEM_TM10_HIDDEN_POWER     298
#define ITEM_TM11_SUNNY_DAY        299
#define ITEM_TM12_TAUNT            300
#define ITEM_TM13_ICE_BEAM         301
#define ITEM_TM14_BLIZZARD         302
#define ITEM_TM15_HYPER_BEAM       303
#define ITEM_TM16_LIGHT_SCREEN     304
#define ITEM_TM17_PROTECT          305
#define ITEM_TM18_RAIN_DANCE       306
#define ITEM_TM19_GIGA_DRAIN       307
#define ITEM_TM20_SAFEGUARD        308
#define ITEM_TM21_FRUSTRATION      309
#define ITEM_TM22_SOLARBEAM        310
#define ITEM_TM23_IRON_TAIL        311
#define ITEM_TM24_THUNDERBOLT      312
#define ITEM_TM25_THUNDER          313
#define ITEM_TM26_EARTHQUAKE       314
#define ITEM_TM27_RETURN           315
#define ITEM_TM28_DIG              316
#define ITEM_TM29_PSYCHIC          317
#define ITEM_TM30_SHADOW_BALL      318
#define ITEM_TM31_BRICK_BREAK      319
#define ITEM_TM32_DOUBLE_TEAM      320
#define ITEM_TM33_REFLECT          321
#define ITEM_TM34_SHOCK_WAVE       322
#define ITEM_TM35_FLAMETHROWER     323
#define ITEM_TM36_SLUDGE_BOMB      324
#define ITEM_TM37_SANDSTORM        325
#define ITEM_TM38_FIRE_BLAST       326
#define ITEM_TM39_ROCK_TOMB        327
#define ITEM_TM40_AERIAL_ACE       328
#define ITEM_TM41_TORMENT          329
#define ITEM_TM42_FACADE           330
#define ITEM_TM43_SECRET_POWER     331
#define ITEM_TM44_REST             332
#define ITEM_TM45_ATTRACT          333
#define ITEM_TM46_THIEF            334
#define ITEM_TM47_STEEL_WING       335
#define ITEM_TM48_SKILL_SWAP       336
#define ITEM_TM49_SNATCH           337
#define ITEM_TM50_OVERHEAT         338
#define ITEM_TM51_ROOST            339
#define ITEM_TM52_FOCUS_BLAST      340
#define ITEM_TM53_ENERGY_BALL      341
#define ITEM_TM54_FALSE_SWIPE      342
#define ITEM_TM55_BRINE            343
#define ITEM_TM56_FLING            344
#define ITEM_TM57_CHARGE_BEAM      345
#define ITEM_TM58_ENDURE           346
#define ITEM_TM59_DRAGON_PULSE     347
#define ITEM_TM60_DRAIN_PUNCH      348
#define ITEM_TM61_WILL_O_WISP      349
#define ITEM_TM62_SILVER_WIND      350
#define ITEM_TM63_EMBARGO          351
#define ITEM_TM64_EXPLOSION        352
#define ITEM_TM65_SHADOW_CLAW      353
#define ITEM_TM66_PAYBACK          354
#define ITEM_TM67_RECYCLE          355
#define ITEM_TM68_GIGA_IMPACT      356
#define ITEM_TM69_ROCK_POLISH      357
#define ITEM_TM70_FLASH            358
#define ITEM_TM71_STONE_EDGE       359
#define ITEM_TM72_AVALANCHE        360
#define ITEM_TM73_THUNDER_WAVE     361
#define ITEM_TM74_GYRO_BALL        362
#define ITEM_TM75_SWORDS_DANCE     363
#define ITEM_TM76_STEALTH_ROCK     364
#define ITEM_TM77_PSYCH_UP         365
#define ITEM_TM78_CAPTIVATE        366
#define ITEM_TM79_DARK_PULSE       367
#define ITEM_TM80_ROCK_SLIDE       368
#define ITEM_TM81_X_SCISSOR        369
#define ITEM_TM82_SLEEP_TALK       370
#define ITEM_TM83_NATURAL_GIFT     371
#define ITEM_TM84_POISON_JAB       372
#define ITEM_TM85_DREAM_EATER      373
#define ITEM_TM86_GRASS_KNOT       374
#define ITEM_TM87_SWAGGER          375
#define ITEM_TM88_PLUCK            376
#define ITEM_TM89_U_TURN           377
#define ITEM_TM90_SUBSTITUTE       378
#define ITEM_TM91_FLASH_CANNON     379
#define ITEM_TM92_TRICK_ROOM       380
#define ITEM_HM01_CUT              381
#define ITEM_HM02_FLY              382
#define ITEM_HM03_SURF             383
#define ITEM_HM04_STRENGTH         384
#define ITEM_HM05_FLASH            385
#define ITEM_HM06_ROCK_SMASH       386
#define ITEM_HM07_WATERFALL        387
#define ITEM_HM08_DIVE             388

// Alternative labels for the TMs/HMs, because it's easier to do "giveitem ITEM_TM01, 1" than "giveitem ITEM_TM01_FOCUS_PUNCH, 1"
#define ITEM_TM01                  ITEM_TM01_FOCUS_PUNCH
#define ITEM_TM02                  ITEM_TM02_DRAGON_CLAW
#define ITEM_TM03                  ITEM_TM03_WATER_PULSE
#define ITEM_TM04                  ITEM_TM04_CALM_MIND
#define ITEM_TM05                  ITEM_TM05_ROAR
#define ITEM_TM06                  ITEM_TM06_TOXIC
#define ITEM_TM07                  ITEM_TM07_HAIL
#define ITEM_TM08                  ITEM_TM08_BULK_UP
#define ITEM_TM09                  ITEM_TM09_BULLET_SEED
#define ITEM_TM10                  ITEM_TM10_HIDDEN_POWER
#define ITEM_TM11                  ITEM_TM11_SUNNY_DAY
#define ITEM_TM12                  ITEM_TM12_TAUNT
#define ITEM_TM13                  ITEM_TM13_ICE_BEAM
#define ITEM_TM14                  ITEM_TM14_BLIZZARD
#define ITEM_TM15                  ITEM_TM15_HYPER_BEAM
#define ITEM_TM16                  ITEM_TM16_LIGHT_SCREEN
#define ITEM_TM17                  ITEM_TM17_PROTECT
#define ITEM_TM18                  ITEM_TM18_RAIN_DANCE
#define ITEM_TM19                  ITEM_TM19_GIGA_DRAIN
#define ITEM_TM20                  ITEM_TM20_SAFEGUARD
#define ITEM_TM21                  ITEM_TM21_FRUSTRATION
#define ITEM_TM22                  ITEM_TM22_SOLARBEAM
#define ITEM_TM23                  ITEM_TM23_IRON_TAIL
#define ITEM_TM24                  ITEM_TM24_THUNDERBOLT
#define ITEM_TM25                  ITEM_TM25_THUNDER
#define ITEM_TM26                  ITEM_TM26_EARTHQUAKE
#define ITEM_TM27                  ITEM_TM27_RETURN
#define ITEM_TM28                  ITEM_TM28_DIG
#define ITEM_TM29                  ITEM_TM29_PSYCHIC
#define ITEM_TM30                  ITEM_TM30_SHADOW_BALL
#define ITEM_TM31                  ITEM_TM31_BRICK_BREAK
#define ITEM_TM32                  ITEM_TM32_DOUBLE_TEAM
#define ITEM_TM33                  ITEM_TM33_REFLECT
#define ITEM_TM34                  ITEM_TM34_SHOCK_WAVE
#define ITEM_TM35                  ITEM_TM35_FLAMETHROWER
#define ITEM_TM36                  ITEM_TM36_SLUDGE_BOMB
#define ITEM_TM37                  ITEM_TM37_SANDSTORM
#define ITEM_TM38                  ITEM_TM38_FIRE_BLAST
#define ITEM_TM39                  ITEM_TM39_ROCK_TOMB
#define ITEM_TM40                  ITEM_TM40_AERIAL_ACE
#define ITEM_TM41                  ITEM_TM41_TORMENT
#define ITEM_TM42                  ITEM_TM42_FACADE
#define ITEM_TM43                  ITEM_TM43_SECRET_POWER
#define ITEM_TM44                  ITEM_TM44_REST
#define ITEM_TM45                  ITEM_TM45_ATTRACT
#define ITEM_TM46                  ITEM_TM46_THIEF
#define ITEM_TM47                  ITEM_TM47_STEEL_WING
#define ITEM_TM48                  ITEM_TM48_SKILL_SWAP
#define ITEM_TM49                  ITEM_TM49_SNATCH
#define ITEM_TM50                  ITEM_TM50_OVERHEAT
#define ITEM_TM51                  ITEM_TM51_ROOST
#define ITEM_TM52                  ITEM_TM52_FOCUS_BLAST
#define ITEM_TM53                  ITEM_TM53_ENERGY_BALL
#define ITEM_TM54                  ITEM_TM54_FALSE_SWIPE
#define ITEM_TM55                  ITEM_TM55_BRINE
#define ITEM_TM56                  ITEM_TM56_FLING
#define ITEM_TM57                  ITEM_TM57_CHARGE_BEAM
#define ITEM_TM58                  ITEM_TM58_ENDURE
#define ITEM_TM59                  ITEM_TM59_DRAGON_PULSE
#define ITEM_TM60                  ITEM_TM60_DRAIN_PUNCH
#define ITEM_TM61                  ITEM_TM61_WILL_O_WISP
#define ITEM_TM62                  ITEM_TM62_SILVER_WIND
#define ITEM_TM63                  ITEM_TM63_EMBARGO
#define ITEM_TM64                  ITEM_TM64_EXPLOSION
#define ITEM_TM65                  ITEM_TM65_SHADOW_CLAW
#define ITEM_TM66                  ITEM_TM66_PAYBACK
#define ITEM_TM67                  ITEM_TM67_RECYCLE
#define ITEM_TM68                  ITEM_TM68_GIGA_IMPACT
#define ITEM_TM69                  ITEM_TM69_ROCK_POLISH
#define ITEM_TM70                  ITEM_TM70_FLASH
#define ITEM_TM71                  ITEM_TM71_STONE_EDGE
#define ITEM_TM72                  ITEM_TM72_AVALANCHE
#define ITEM_TM73                  ITEM_TM73_THUNDER_WAVE
#define ITEM_TM74                  ITEM_TM74_GYRO_BALL
#define ITEM_TM75                  ITEM_TM75_SWORDS_DANCE
#define ITEM_TM76                  ITEM_TM76_STEALTH_ROCK
#define ITEM_TM77                  ITEM_TM77_PSYCH_UP
#define ITEM_TM78                  ITEM_TM78_CAPTIVATE
#define ITEM_TM79                  ITEM_TM79_DARK_PULSE
#define ITEM_TM80                  ITEM_TM80_ROCK_SLIDE
#define ITEM_TM81                  ITEM_TM81_X_SCISSOR
#define ITEM_TM82                  ITEM_TM82_SLEEP_TALK
#define ITEM_TM83                  ITEM_TM83_NATURAL_GIFT
#define ITEM_TM84                  ITEM_TM84_POISON_JAB
#define ITEM_TM85                  ITEM_TM85_DREAM_EATER
#define ITEM_TM86                  ITEM_TM86_GRASS_KNOT
#define ITEM_TM87                  ITEM_TM87_SWAGGER
#define ITEM_TM88                  ITEM_TM88_PLUCK
#define ITEM_TM89                  ITEM_TM89_U_TURN
#define ITEM_TM90                  ITEM_TM90_SUBSTITUTE
#define ITEM_TM91                  ITEM_TM91_FLASH_CANNON
#define ITEM_TM92                  ITEM_TM92_TRICK_ROOM
#define ITEM_HM01                  ITEM_HM01_CUT
#define ITEM_HM02                  ITEM_HM02_FLY
#define ITEM_HM03                  ITEM_HM03_SURF
#define ITEM_HM04                  ITEM_HM04_STRENGTH
#define ITEM_HM05                  ITEM_HM05_FLASH
#define ITEM_HM06                  ITEM_HM06_ROCK_SMASH
#define ITEM_HM07                  ITEM_HM07_WATERFALL
#define ITEM_HM08                  ITEM_HM08_DIVE

#define NUM_TECHNICAL_MACHINES      92
#define NUM_HIDDEN_MACHINES          8

// Unknown
#define ITEM_15B 389
#define ITEM_15C 390

#define NUM_OF_ITEMS 391 

// Check if the item is one that can be used on a Pokemon.
#define IS_POKEMON_ITEM(item) ((item) >= ITEM_POTION && (item) <= ITEM_ENIGMA_BERRY)

#define IS_ITEM_MAIL(item) ((item) >= ITEM_ORANGE_MAIL && (item) <= ITEM_RETRO_MAIL)

#endif  // GUARD_CONSTANTS_ITEMS_H
