gAbilityNames:: @ 81FA248
	.string "-------$", 13
	.string "STENCH$", 13
	.string "DRIZZLE$", 13
	.string "SPEED BOOST$", 13
	.string "BATTLE ARMOR$", 13
	.string "STURDY$", 13
	.string "DAMP$", 13
	.string "LIMBER$", 13
	.string "SAND VEIL$", 13
	.string "STATIC$", 13
	.string "VOLT ABSORB$", 13
	.string "WATER ABSORB$", 13
	.string "OBLIVIOUS$", 13
	.string "CLOUD NINE$", 13
	.string "COMPOUNDEYES$", 13
	.string "INSOMNIA$", 13
	.string "COLOR CHANGE$", 13
	.string "IMMUNITY$", 13
	.string "FLASH FIRE$", 13
	.string "SHIELD DUST$", 13
	.string "OWN TEMPO$", 13
	.string "SUCTION CUPS$", 13
	.string "INTIMIDATE$", 13
	.string "SHADOW TAG$", 13
	.string "ROUGH SKIN$", 13
	.string "WONDER GUARD$", 13
	.string "LEVITATE$", 13
	.string "EFFECT SPORE$", 13
	.string "SYNCHRONIZE$", 13
	.string "CLEAR BODY$", 13
	.string "NATURAL CURE$", 13
	.string "LIGHTNINGROD$", 13
	.string "SERENE GRACE$", 13
	.string "SWIFT SWIM$", 13
	.string "CHLOROPHYLL$", 13
	.string "ILLUMINATE$", 13
	.string "TRACE$", 13
	.string "HUGE POWER$", 13
	.string "POISON POINT$", 13
	.string "INNER FOCUS$", 13
	.string "MAGMA ARMOR$", 13
	.string "WATER VEIL$", 13
	.string "MAGNET PULL$", 13
	.string "SOUNDPROOF$", 13
	.string "RAIN DISH$", 13
	.string "SAND STREAM$", 13
	.string "PRESSURE$", 13
	.string "THICK FAT$", 13
	.string "EARLY BIRD$", 13
	.string "FLAME BODY$", 13
	.string "RUN AWAY$", 13
	.string "KEEN EYE$", 13
	.string "HYPER CUTTER$", 13
	.string "PICKUP$", 13
	.string "TRUANT$", 13
	.string "HUSTLE$", 13
	.string "CUTE CHARM$", 13
	.string "PLUS$", 13
	.string "MINUS$", 13
	.string "FORECAST$", 13
	.string "STICKY HOLD$", 13
	.string "SHED SKIN$", 13
	.string "GUTS$", 13
	.string "MARVEL SCALE$", 13
	.string "LIQUID OOZE$", 13
	.string "OVERGROW$", 13
	.string "BLAZE$", 13
	.string "TORRENT$", 13
	.string "SWARM$", 13
	.string "ROCK HEAD$", 13
	.string "DROUGHT$", 13
	.string "ARENA TRAP$", 13
	.string "VITAL SPIRIT$", 13
	.string "WHITE SMOKE$", 13
	.string "PURE POWER$", 13
	.string "SHELL ARMOR$", 13
	.string "CACOPHONY$", 13
	.string "AIR LOCK$", 13
	.string "ADAPTABILITY$", 13
	.string "AFTERMATH$", 13
	.string "ANGER POINT$", 13
	.string "ANTICIPATION$", 13 @ Placeholder
	.string "BAD DREAMS$", 13
	.string "DOWNLOAD$", 13 @ Placeholder
	.string "DRY SKIN$", 13
	.string "FILTER$", 13
	.string "FLOWER GIFT$", 13
	.string "FOREWARN$", 13 @ Placeholder
	.string "FRISK$", 13 @ Placeholder
	.string "GLUTTONY$", 13
	.string "HEATPROOF$", 13
	.string "HONEY GATHER$", 13
	.string "HYDRATION$", 13
	.string "ICE BODY$", 13
	.string "IRON FIST$", 13
	.string "KLUTZ$", 13 @ Placeholder
	.string "LEAF GUARD$", 13 @ Placeholder
	.string "MAGIC GUARD$", 13 @ Placeholder
	.string "MOLD BREAKER$", 13 @ Placeholder
	.string "MOTOR DRIVE$", 13
	.string "MULTITYPE$", 13 @ Placeholder
	.string "NO GUARD$", 13
	.string "NORMALIZE$", 13
	.string "POISON HEAL$", 13
	.string "QUICK FEET$", 13
	.string "RECKLESS$", 13
	.string "RIVALRY$", 13
	.string "SCRAPPY$", 13
	.string "SIMPLE$", 13
	.string "SKILL LINK$", 13
	.string "SLOW START$", 13
	.string "SNIPER$", 13
	.string "SNOW CLOAK$", 13
	.string "SNOW WARNING$", 13
	.string "SOLAR POWER$", 13
	.string "SOLID ROCK$", 13
	.string "STALL$", 13 @ Placeholder
	.string "STEADFAST$", 13 @ Placeholder
	.string "STORM DRAIN$", 13 @ Placeholder
	.string "SUPER LUCK$", 13
	.string "TANGLED FEET$", 13
	.string "TECHNICIAN$", 13
	.string "TINTED LENS$", 13
	.string "UNAWARE$", 13 @ Placeholder
	.string "UNBURDEN$", 13 @ Placeholder
