	.align 2
gMonBackPicCoords:: @ 81E9114
	.byte 136,  0, 0, 0 // SPECIES_NONE
	.byte 100, 16, 0, 0 // SPECIES_BULBASAUR
	.byte 102,  9, 0, 0 // SPECIES_IVYSAUR
	.byte 135,  7, 0, 0 // SPECIES_VENUSAUR
	.byte 101, 14, 0, 0 // SPECIES_CHARMANDER
	.byte 102,  9, 0, 0 // SPECIES_CHARMELEON
	.byte 135,  4, 0, 0 // SPECIES_CHARIZARD
	.byte 101, 14, 0, 0 // SPECIES_SQUIRTLE
	.byte 118, 10, 0, 0 // SPECIES_WARTORTLE
	.byte 135,  7, 0, 0 // SPECIES_BLASTOISE
	.byte  85, 13, 0, 0 // SPECIES_CATERPIE
	.byte 101, 12, 0, 0 // SPECIES_METAPOD
	.byte 119,  6, 0, 0 // SPECIES_BUTTERFREE
	.byte  86, 12, 0, 0 // SPECIES_WEEDLE
	.byte  70, 12, 0, 0 // SPECIES_KAKUNA
	.byte 134,  9, 0, 0 // SPECIES_BEEDRILL
	.byte 102, 12, 0, 0 // SPECIES_PIDGEY
	.byte 133, 10, 0, 0 // SPECIES_PIDGEOTTO
	.byte 120,  8, 0, 0 // SPECIES_PIDGEOT
	.byte 101, 13, 0, 0 // SPECIES_RATTATA
	.byte 117, 13, 0, 0 // SPECIES_RATICATE
	.byte 101, 12, 0, 0 // SPECIES_SPEAROW
	.byte 135,  5, 0, 0 // SPECIES_FEAROW
	.byte 102, 12, 0, 0 // SPECIES_EKANS
	.byte 119,  4, 0, 0 // SPECIES_ARBOK
	.byte 119,  7, 0, 0 // SPECIES_PIKACHU
	.byte 102,  8, 0, 0 // SPECIES_RAICHU
	.byte 101, 15, 0, 0 // SPECIES_SANDSHREW
	.byte 134, 12, 0, 0 // SPECIES_SANDSLASH
	.byte  85, 14, 0, 0 // SPECIES_NIDORAN_F
	.byte 134, 10, 0, 0 // SPECIES_NIDORINA
	.byte 119,  6, 0, 0 // SPECIES_NIDOQUEEN
	.byte  85, 11, 0, 0 // SPECIES_NIDORAN_M
	.byte 134, 10, 0, 0 // SPECIES_NIDORINO
	.byte 119,  6, 0, 0 // SPECIES_NIDOKING
	.byte 101, 15, 0, 0 // SPECIES_CLEFAIRY
	.byte 118, 10, 0, 0 // SPECIES_CLEFABLE
	.byte 118,  9, 0, 0 // SPECIES_VULPIX
	.byte 119,  6, 0, 0 // SPECIES_NINETALES
	.byte 101,  8, 0, 0 // SPECIES_JIGGLYPUFF
	.byte 118, 10, 0, 0 // SPECIES_WIGGLYTUFF
	.byte 118, 11, 0, 0 // SPECIES_ZUBAT
	.byte 135, 13, 0, 0 // SPECIES_GOLBAT
	.byte  86, 11, 0, 0 // SPECIES_ODDISH
	.byte 102, 12, 0, 0 // SPECIES_GLOOM
	.byte 135,  7, 0, 0 // SPECIES_VILEPLUME
	.byte  99, 20, 0, 0 // SPECIES_PARAS
	.byte 135, 14, 0, 0 // SPECIES_PARASECT
	.byte 119,  6, 0, 0 // SPECIES_VENONAT
	.byte 119,  4, 0, 0 // SPECIES_VENOMOTH
	.byte  84, 16, 0, 0 // SPECIES_DIGLETT
	.byte 102, 22, 0, 0 // SPECIES_DUGTRIO
	.byte 101, 12, 0, 0 // SPECIES_MEOWTH
	.byte 135,  7, 0, 0 // SPECIES_PERSIAN
	.byte 103, 11, 0, 0 // SPECIES_PSYDUCK
	.byte 119,  5, 0, 0 // SPECIES_GOLDUCK
	.byte 118, 11, 0, 0 // SPECIES_MANKEY
	.byte 119, 11, 0, 0 // SPECIES_PRIMEAPE
	.byte 102,  8, 0, 0 // SPECIES_GROWLITHE
	.byte 135,  6, 0, 0 // SPECIES_ARCANINE
	.byte 116, 20, 0, 0 // SPECIES_POLIWAG
	.byte 101, 15, 0, 0 // SPECIES_POLIWHIRL
	.byte 134, 11, 0, 0 // SPECIES_POLIWRATH
	.byte 102, 14, 0, 0 // SPECIES_ABRA
	.byte 118,  8, 0, 0 // SPECIES_KADABRA
	.byte 103,  8, 0, 0 // SPECIES_ALAKAZAM
	.byte 101, 12, 0, 0 // SPECIES_MACHOP
	.byte 118,  9, 0, 0 // SPECIES_MACHOKE
	.byte 103,  8, 0, 0 // SPECIES_MACHAMP
	.byte 102, 12, 0, 0 // SPECIES_BELLSPROUT
	.byte 102, 13, 0, 0 // SPECIES_WEEPINBELL
	.byte 135,  6, 0, 0 // SPECIES_VICTREEBEL
	.byte  86, 10, 0, 0 // SPECIES_TENTACOOL 
	.byte 134, 11, 0, 0 // SPECIES_TENTACRUEL
	.byte 102, 11, 0, 0 // SPECIES_GEODUDE 74
	.byte 117, 12, 0, 0 // SPECIES_GRAVELER 7
	.byte 132, 16, 0, 0 // SPECIES_GOLEM 76
	.byte 102,  9, 0, 0 // SPECIES_PONYTA 77
	.byte 135,  5, 0, 0 // SPECIES_RAPIDASH 7
	.byte 133, 14, 0, 0 // SPECIES_SLOWPOKE 7
	.byte 134, 10, 0, 0 // SPECIES_SLOWBRO 80
	.byte  67, 20, 0, 0 // SPECIES_MAGNEMITE 
	.byte 102, 10, 0, 0 // SPECIES_MAGNETON 8
	.byte 102, 10, 0, 0 // SPECIES_FARFETCHD 
	.byte 102,  8, 0, 0 // SPECIES_DODUO 84
	.byte 136,  1, 0, 0 // SPECIES_DODRIO 85
	.byte 102, 10, 0, 0 // SPECIES_SEEL 86
	.byte 119,  5, 0, 0 // SPECIES_DEWGONG 87
	.byte 117, 12, 0, 0 // SPECIES_GRIMER 88
	.byte 135,  5, 0, 0 // SPECIES_MUK 89
	.byte 118, 11, 0, 0 // SPECIES_SHELLDER 9
	.byte 135,  6, 0, 0 // SPECIES_CLOYSTER 9
	.byte 133, 14, 0, 0 // SPECIES_GASTLY 92
	.byte 118,  8, 0, 0 // SPECIES_HAUNTER 93
	.byte 118,  9, 0, 0 // SPECIES_GENGAR 94
	.byte 120,  0, 0, 0 // SPECIES_ONIX 95
	.byte 101, 13, 0, 0 // SPECIES_DROWZEE 96
	.byte 102,  9, 0, 0 // SPECIES_HYPNO 97
	.byte 102, 10, 0, 0 // SPECIES_KRABBY 98
	.byte 119,  4, 0, 0 // SPECIES_KINGLER 99
	.byte  85, 14, 0, 0 // SPECIES_VOLTORB 10
	.byte 101, 13, 0, 0 // SPECIES_ELECTRODE 
	.byte 101, 13, 0, 0 // SPECIES_EXEGGCUTE 
	.byte 135,  4, 0, 0 // SPECIES_EXEGGUTOR 
	.byte 102, 10, 0, 0 // SPECIES_CUBONE 104
	.byte 102,  8, 0, 0 // SPECIES_MAROWAK 10
	.byte 101, 12, 0, 0 // SPECIES_HITMONLEE 
	.byte 101, 12, 0, 0 // SPECIES_HITMONCHAN
	.byte 101, 14, 0, 0 // SPECIES_LICKITUNG 
	.byte 102,  9, 0, 0 // SPECIES_KOFFING 10
	.byte 119,  6, 0, 0 // SPECIES_WEEZING 11
	.byte 133, 12, 0, 0 // SPECIES_RHYHORN 11
	.byte 136,  3, 0, 0 // SPECIES_RHYDON 112
	.byte 134, 11, 0, 0 // SPECIES_CHANSEY 11
	.byte 133, 14, 0, 0 // SPECIES_TANGELA 11
	.byte 119,  5, 0, 0 // SPECIES_KANGASKHAN
	.byte 102,  9, 0, 0 // SPECIES_HORSEA 116
	.byte 102,  8, 0, 0 // SPECIES_SEADRA 117
	.byte 102,  8, 0, 0 // SPECIES_GOLDEEN 11
	.byte 118, 11, 0, 0 // SPECIES_SEAKING 11
	.byte 101, 13, 0, 0 // SPECIES_STARYU 120
	.byte 133, 14, 0, 0 // SPECIES_STARMIE 12
	.byte 133, 13, 0, 0 // SPECIES_MR_MIME 12
	.byte 119,  7, 0, 0 // SPECIES_SCYTHER 12
	.byte 134, 10, 0, 0 // SPECIES_JYNX 124
	.byte 102,  8, 0, 0 // SPECIES_ELECTABUZZ
	.byte 102,  8, 0, 0 // SPECIES_MAGMAR 126
	.byte 102,  9, 0, 0 // SPECIES_PINSIR 127
	.byte 133, 13, 0, 0 // SPECIES_TAUROS 128
	.byte 118,  9, 0, 0 // SPECIES_MAGIKARP 1
	.byte 120,  0, 0, 0 // SPECIES_GYARADOS 1
	.byte 119,  4, 0, 0 // SPECIES_LAPRAS 131
	.byte  84, 17, 0, 0 // SPECIES_DITTO 132
	.byte 102, 10, 0, 0 // SPECIES_EEVEE 133
	.byte 102, 10, 0, 0 // SPECIES_VAPOREON 1
	.byte 135,  6, 0, 0 // SPECIES_JOLTEON 13
	.byte 103,  5, 0, 0 // SPECIES_FLAREON 13
	.byte 101, 13, 0, 0 // SPECIES_PORYGON 13
	.byte 102, 10, 0, 0 // SPECIES_OMANYTE 13
	.byte 102,  8, 0, 0 // SPECIES_OMASTAR 13
	.byte 101, 13, 0, 0 // SPECIES_KABUTO 140
	.byte 119,  5, 0, 0 // SPECIES_KABUTOPS 1
	.byte 134,  8, 0, 0 // SPECIES_AERODACTYL
	.byte 134, 11, 0, 0 // SPECIES_SNORLAX 14
	.byte 101, 12, 0, 0 // SPECIES_ARTICUNO 1
	.byte 118, 11, 0, 0 // SPECIES_ZAPDOS 145
	.byte 135,  4, 0, 0 // SPECIES_MOLTRES 14
	.byte 102,  9, 0, 0 // SPECIES_DRATINI 14
	.byte 120,  0, 0, 0 // SPECIES_DRAGONAIR 
	.byte 135,  6, 0, 0 // SPECIES_DRAGONITE 
	.byte 120,  1, 0, 0 // SPECIES_MEWTWO 150
	.byte 102,  8, 0, 0 // SPECIES_MEW 151
	.byte  86, 10, 0, 0 // SPECIES_CHIKORITA 
	.byte 102,  8, 0, 0 // SPECIES_BAYLEEF 15
	.byte 120,  0, 0, 0 // SPECIES_MEGANIUM 1
	.byte 118,  9, 0, 0 // SPECIES_CYNDAQUIL 
	.byte 135,  4, 0, 0 // SPECIES_QUILAVA 15
	.byte 135,  4, 0, 0 // SPECIES_TYPHLOSION
	.byte 102, 11, 0, 0 // SPECIES_TOTODILE 1
	.byte 103,  7, 0, 0 // SPECIES_CROCONAW 1
	.byte 136,  1, 0, 0 // SPECIES_FERALIGATR
	.byte 103,  5, 0, 0 // SPECIES_SENTRET 16
	.byte 102,  8, 0, 0 // SPECIES_FURRET 162
	.byte 102,  8, 0, 0 // SPECIES_HOOTHOOT 1
	.byte 104,  3, 0, 0 // SPECIES_NOCTOWL 16
	.byte 118, 11, 0, 0 // SPECIES_LEDYBA 165
	.byte 119,  7, 0, 0 // SPECIES_LEDIAN 166
	.byte 115, 21, 0, 0 // SPECIES_SPINARAK 1
	.byte 134, 11, 0, 0 // SPECIES_ARIADOS 16
	.byte 135,  5, 0, 0 // SPECIES_CROBAT 169
	.byte 134,  8, 0, 0 // SPECIES_CHINCHOU 1
	.byte 134,  8, 0, 0 // SPECIES_LANTURN 17
	.byte 102, 11, 0, 0 // SPECIES_PICHU 172
	.byte 101, 15, 0, 0 // SPECIES_CLEFFA 173
	.byte 102, 11, 0, 0 // SPECIES_IGGLYBUFF 
	.byte  84, 16, 0, 0 // SPECIES_TOGEPI 175
	.byte 102,  8, 0, 0 // SPECIES_TOGETIC 17
	.byte  84, 17, 0, 0 // SPECIES_NATU 177
	.byte 118,  8, 0, 0 // SPECIES_XATU 178
	.byte 102,  9, 0, 0 // SPECIES_MAREEP 179
	.byte 102,  9, 0, 0 // SPECIES_FLAAFFY 18
	.byte 136,  1, 0, 0 // SPECIES_AMPHAROS 1
	.byte 102, 11, 0, 0 // SPECIES_BELLOSSOM 
	.byte 117, 12, 0, 0 // SPECIES_MARILL 183
	.byte 134,  8, 0, 0 // SPECIES_AZUMARILL 
	.byte 102,  8, 0, 0 // SPECIES_SUDOWOODO 
	.byte 102,  9, 0, 0 // SPECIES_POLITOED 1
	.byte 102, 11, 0, 0 // SPECIES_HOPPIP 187
	.byte 101, 13, 0, 0 // SPECIES_SKIPLOOM 1
	.byte 135,  4, 0, 0 // SPECIES_JUMPLUFF 1
	.byte 102,  9, 0, 0 // SPECIES_AIPOM 190
	.byte  86, 10, 0, 0 // SPECIES_SUNKERN 19
	.byte 102,  8, 0, 0 // SPECIES_SUNFLORA 1
	.byte 119,  4, 0, 0 // SPECIES_YANMA 193
	.byte 133, 15, 0, 0 // SPECIES_WOOPER 194
	.byte 118,  8, 0, 0 // SPECIES_QUAGSIRE 1
	.byte 118, 11, 0, 0 // SPECIES_ESPEON 196
	.byte 135,  4, 0, 0 // SPECIES_UMBREON 19
	.byte 102,  9, 0, 0 // SPECIES_MURKROW 19
	.byte 102,  8, 0, 0 // SPECIES_SLOWKING 1
	.byte 102, 10, 0, 0 // SPECIES_MISDREAVUS
	.byte  54,  8, 0, 0 // SPECIES_UNOWN 201
	.byte 117, 12, 0, 0 // SPECIES_WOBBUFFET 
	.byte 135,  5, 0, 0 // SPECIES_GIRAFARIG 
	.byte 101, 15, 0, 0 // SPECIES_PINECO 204
	.byte 132, 16, 0, 0 // SPECIES_FORRETRESS
	.byte 133, 15, 0, 0 // SPECIES_DUNSPARCE 
	.byte 135,  5, 0, 0 // SPECIES_GLIGAR 207
	.byte 136,  0, 0, 0 // SPECIES_STEELIX 20
	.byte 118, 10, 0, 0 // SPECIES_SNUBBULL 2
	.byte 135,  5, 0, 0 // SPECIES_GRANBULL 2
	.byte 119,  7, 0, 0 // SPECIES_QWILFISH 2
	.byte 119,  4, 0, 0 // SPECIES_SCIZOR 212
	.byte  86, 11, 0, 0 // SPECIES_SHUCKLE 21
	.byte 119,  4, 0, 0 // SPECIES_HERACROSS 
	.byte 102,  8, 0, 0 // SPECIES_SNEASEL 21
	.byte 102,  8, 0, 0 // SPECIES_TEDDIURSA 
	.byte 136,  3, 0, 0 // SPECIES_URSARING 2
	.byte 102,  8, 0, 0 // SPECIES_SLUGMA 218
	.byte 118,  9, 0, 0 // SPECIES_MAGCARGO 2
	.byte  99, 21, 0, 0 // SPECIES_SWINUB 220
	.byte 117, 13, 0, 0 // SPECIES_PILOSWINE 
	.byte 101, 12, 0, 0 // SPECIES_CORSOLA 22
	.byte 117, 13, 0, 0 // SPECIES_REMORAID 2
	.byte 102, 10, 0, 0 // SPECIES_OCTILLERY 
	.byte 103,  6, 0, 0 // SPECIES_DELIBIRD 2
	.byte 135,  7, 0, 0 // SPECIES_MANTINE 22
	.byte 135,  4, 0, 0 // SPECIES_SKARMORY 2
	.byte  85, 12, 0, 0 // SPECIES_HOUNDOUR 2
	.byte 135,  7, 0, 0 // SPECIES_HOUNDOOM 2
	.byte 135,  6, 0, 0 // SPECIES_KINGDRA 23
	.byte 101, 14, 0, 0 // SPECIES_PHANPY 231
	.byte 133, 13, 0, 0 // SPECIES_DONPHAN 23
	.byte 118, 10, 0, 0 // SPECIES_PORYGON2 2
	.byte 120,  3, 0, 0 // SPECIES_STANTLER 2
	.byte 118, 10, 0, 0 // SPECIES_SMEARGLE 2
	.byte 102,  8, 0, 0 // SPECIES_TYROGUE 23
	.byte 135,  5, 0, 0 // SPECIES_HITMONTOP 
	.byte  86,  9, 0, 0 // SPECIES_SMOOCHUM 2
	.byte 102,  8, 0, 0 // SPECIES_ELEKID 239
	.byte 102, 11, 0, 0 // SPECIES_MAGBY 240
	.byte 135,  7, 0, 0 // SPECIES_MILTANK 24
	.byte 133, 13, 0, 0 // SPECIES_BLISSEY 24
	.byte 134, 10, 0, 0 // SPECIES_RAIKOU 243
	.byte 135,  6, 0, 0 // SPECIES_ENTEI 244
	.byte 136,  3, 0, 0 // SPECIES_SUICUNE 24
	.byte 102,  8, 0, 0 // SPECIES_LARVITAR 2
	.byte 103,  5, 0, 0 // SPECIES_PUPITAR 24
	.byte 136,  0, 0, 0 // SPECIES_TYRANITAR 
	.byte 136,  1, 0, 0 // SPECIES_LUGIA 249
	.byte 136,  1, 0, 0 // SPECIES_HO_OH 250
	.byte 102,  8, 0, 0 // SPECIES_CELEBI 251
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  2, 0, 0
	.byte 135,  6, 0, 0
	.byte 134,  8, 0, 0
	.byte 136,  1, 0, 0
	.byte 103,  5, 0, 0
	.byte 136,  0, 0, 0
	.byte 136,  0, 0, 0
	.byte 119,  5, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  5, 0, 0
	.byte 118,  9, 0, 0
	.byte 135,  4, 0, 0
	.byte 118, 11, 0, 0
	.byte 133, 15, 0, 0
	.byte 118, 11, 0, 0
	.byte 131, 21, 0, 0
	.byte 136,  0, 0, 0
	.byte 115, 20, 0, 0
	.byte 131, 20, 0, 0
	.byte 117, 15, 0, 0
	.byte 134,  8, 0, 0
	.byte 134, 10, 0, 0
	.byte 134,  9, 0, 0
	.byte 118, 10, 0, 0
	.byte 134,  8, 0, 0
	.byte 131, 20, 0, 0
	.byte 134,  8, 0, 0
	.byte 119,  6, 0, 0
	.byte 100, 17, 0, 0
	.byte 134,  8, 0, 0
	.byte 133, 13, 0, 0
	.byte 135,  4, 0, 0
	.byte 119,  4, 0, 0
	.byte 133, 14, 0, 0
	.byte 135,  6, 0, 0
	.byte 134, 11, 0, 0
	.byte 136,  0, 0, 0
	.byte 131, 21, 0, 0
	.byte 131, 22, 0, 0
	.byte 134, 10, 0, 0
	.byte 134,  8, 0, 0
	.byte 135,  6, 0, 0
	.byte 134,  8, 0, 0
	.byte 135,  7, 0, 0
	.byte 133, 12, 0, 0
	.byte 134, 10, 0, 0
	.byte 118,  8, 0, 0
	.byte 102, 10, 0, 0
	.byte 134, 10, 0, 0
	.byte  70, 10, 0, 0
	.byte 119,  7, 0, 0
	.byte 135,  5, 0, 0
	.byte 103,  7, 0, 0
	.byte 104,  2, 0, 0
	.byte 135,  7, 0, 0
	.byte 136,  2, 0, 0
	.byte 117, 14, 0, 0
	.byte 116, 17, 0, 0
	.byte 136,  2, 0, 0
	.byte 118, 11, 0, 0
	.byte 135,  7, 0, 0
	.byte 132, 16, 0, 0
	.byte 135,  4, 0, 0
	.byte 134, 11, 0, 0
	.byte 132, 19, 0, 0
	.byte 100, 18, 0, 0
	.byte 134, 10, 0, 0
	.byte 135,  6, 0, 0
	.byte 133, 15, 0, 0
	.byte 135,  7, 0, 0
	.byte 118, 10, 0, 0
	.byte 133, 12, 0, 0
	.byte 135,  5, 0, 0
	.byte 135,  5, 0, 0
	.byte 134, 10, 0, 0
	.byte  86, 11, 0, 0
	.byte 135,  4, 0, 0
	.byte 118,  8, 0, 0
	.byte 118,  8, 0, 0
	.byte 135,  4, 0, 0
	.byte 118, 11, 0, 0
	.byte 104,  3, 0, 0
	.byte 134,  9, 0, 0
	.byte 135,  6, 0, 0
	.byte 119,  7, 0, 0
	.byte 102, 11, 0, 0
	.byte 134,  8, 0, 0
	.byte 134,  8, 0, 0
	.byte 133, 15, 0, 0
	.byte 134, 10, 0, 0
	.byte 134,  8, 0, 0
	.byte 102, 11, 0, 0
	.byte 119,  6, 0, 0
	.byte 135,  7, 0, 0
	.byte 133, 13, 0, 0
	.byte 134,  9, 0, 0
	.byte 136,  3, 0, 0
	.byte 133, 13, 0, 0
	.byte 104,  2, 0, 0
	.byte 119,  5, 0, 0
	.byte 120,  3, 0, 0
	.byte 119,  6, 0, 0
	.byte 101, 12, 0, 0
	.byte 136,  3, 0, 0
	.byte 136,  1, 0, 0
	.byte 134, 10, 0, 0
	.byte  84, 17, 0, 0
	.byte 132, 17, 0, 0
	.byte 135,  7, 0, 0
	.byte  69, 13, 0, 0
	.byte 118,  8, 0, 0
	.byte 103,  6, 0, 0
	.byte 134,  9, 0, 0
	.byte 119,  4, 0, 0
	.byte 131, 23, 0, 0
	.byte 119,  5, 0, 0
	.byte  69, 13, 0, 0
	.byte  87,  6, 0, 0
	.byte 119,  4, 0, 0
	.byte 102,  8, 0, 0
	.byte 133, 13, 0, 0
	.byte 119,  6, 0, 0
	.byte 102, 10, 0, 0
	.byte 132, 16, 0, 0
	.byte 131, 20, 0, 0
	.byte 134, 10, 0, 0
	.byte 133, 14, 0, 0
	.byte 133, 14, 0, 0
	.byte 132, 19, 0, 0
	.byte 135,  7, 0, 0
	.byte 120,  0, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  3, 0, 0
	.byte 135,  5, 0, 0
	.byte 134,  9, 0, 0
	.byte  71,  7, 0, 0 // Chimecho
	.byte 136,  8, 0, 0 // Turtwig
	.byte 104, 11, 0, 0 // Grotle
	.byte 135,  7, 0, 0 // Torterra
	.byte 101, 14, 0, 0 // Chimchar
	.byte 102,  9, 0, 0 // Monferno
	.byte 135,  4, 0, 0 // Infernape
	.byte 101, 14, 0, 0 // Piplup
	.byte 118, 10, 0, 0 // Prinplup
	.byte 135,  7, 0, 0 // Empoleon
	.byte 102,  8, 0, 0 // Starly
	.byte 133, 12, 0, 0 // Staravia
	.byte 120,  2, 0, 0 // Staraptor
	.byte  69, 14, 0, 0 // Bidoof
	.byte 133, 12, 0, 0 // Bibarel
	.byte 102,  9, 0, 0 // Kricketot
	.byte 119,  4, 0, 0 // Kricketune
	.byte  86,  8, 0, 0 // Shinx
	.byte 134,  9, 0, 0 // Luxio
	.byte 136,  3, 0, 0 // Luxray
	.byte 119, 14, 0, 0 // Budew
	.byte 102,  8, 0, 0 // Roserade
	.byte 119,  7, 0, 0 // Cranidos
	.byte 102,  8, 0, 0 // Rampardos
	.byte 101, 13, 0, 0 // Shieldon
	.byte 134,  9, 0, 0 // Bastiodon
	.byte  85, 13, 0, 0 // Burmy
	.byte 101, 12, 0, 0 // Wormadam
	.byte 119,  6, 0, 0 // Mothim
	.byte  85, 23, 0, 0 // Combee
	.byte 134,  9, 0, 0 // Vespiquen
	.byte 119,  7, 0, 0 // Pachirisu
	.byte 102,  9, 0, 0 // Buizel
	.byte 119,  8, 0, 0 // Floatzel
	.byte  85, 13, 0, 0 // Cherubi
	.byte 101, 12, 0, 0 // Cherrim
	.byte 102,  7, 0, 0 // Shellos (East)
	.byte 102,  7, 0, 0 // Gastrodon (East)
	.byte  85,  8, 0, 0 // Ambipom
	.byte 101, 12, 0, 0 // Drifloon
	.byte 119,  6, 0, 0 // Drifblim
	.byte 102,  9, 0, 0 // Buneary
	.byte 135,  7, 0, 0 // Lopunny
	.byte 134,  9, 0, 0 // Mismagius
	.byte 120,  9, 0, 0 // Honchkrow
	.byte  69, 14, 0, 0 // Glameow
	.byte 133,  8, 0, 0 // Purugly
	.byte 102,  9, 0, 0 // Chingling
	.byte  69, 14, 0, 0 // Stunky
	.byte 133,  8, 0, 0 // Skuntank
	.byte  85, 13, 0, 0 // Bronzor
	.byte 101, 12, 0, 0 // Bronzong
	.byte 102,  8, 0, 0 // Bonsly
	.byte   0,  8, 0, 0 // Mime Jr.
	.byte 102,  8, 0, 0 // Happiny
	.byte 102,  8, 0, 0 // Chatot
	.byte 101, 12, 0, 0 // Spiritomb
	.byte 101, 14, 0, 0 // Gible
	.byte 102,  9, 0, 0 // Gabite
	.byte 135,  4, 0, 0 // Garchomp
	.byte 102,  8, 0, 0 // Munchlax
	.byte 102,  9, 0, 0 // Riolu
	.byte 119,  4, 0, 0 // Lucario
	.byte 118, 10, 0, 0 // Hippopotas
	.byte 135,  7, 0, 0 // Hippowdon
	.byte 134,  9, 0, 0 // Skorupi
	.byte 136,  6, 0, 0 // Drapion
	.byte  86,  8, 0, 0 // Croagunk
	.byte 134,  9, 0, 0 // Toxicroak
	.byte  85, 13, 0, 0 // Carnivine
	.byte 101, 14, 0, 0 // Finneon
	.byte 118, 10, 0, 0 // Lumineon
	.byte 101, 14, 0, 0 // Mantyke
	.byte 133, 12, 0, 0 // Snover
	.byte 120,  2, 0, 0 // Abomasnow
	.byte 133,  8, 0, 0 // Weavile
	.byte 101, 12, 0, 0 // Magnezone
	.byte 134,  9, 0, 0 // Lickilicky
	.byte 120,  2, 0, 0 // Rhyperior
	.byte 134,  9, 0, 0 // Tangrowth
	.byte 134,  7, 0, 0 // Electivire
	.byte 134,  9, 0, 0 // Magmortar
	.byte 101, 10, 0, 0 // Togekiss
	.byte 101, 10, 0, 0 // Yanmega
	.byte 134,  9, 0, 0 // Leafeon
	.byte 134,  9, 0, 0 // Glaceon
	.byte 101, 10, 0, 0 // Gliscor
	.byte 120,  7, 0, 0 // Mamoswine
	.byte 120,  7, 0, 0 // Porygon-Z
	.byte 134,  4, 0, 0 // Gallade
	.byte 133,  8, 0, 0 // Probopass
	.byte 120,  6, 0, 0 // Dusknoir
	.byte 133,  8, 0, 0 // Froslass
	.byte 101, 10, 0, 0 // Rotom
	.byte 101, 10, 0, 0 // Uxie
	.byte 136, 10, 0, 0 // Mesprit
	.byte 136,  9, 0, 0 // Azelf
	.byte 120,  2, 0, 0 // Dialga
	.byte 120,  7, 0, 0 // Palkia
	.byte 134,  9, 0, 0 // Heatran
	.byte  80,  1, 0, 0 // Regigigas
	.byte 120,  2, 0, 0 // Giratina
	.byte  80,  1, 0, 0 // Cresselia
	.byte 134, 10, 0, 0 // Phione
	.byte 134, 10, 0, 0 // Manaphy
	.byte  80,  1, 0, 0 // Darkrai
	.byte  86,  8, 0, 0 // Shaymin
	.byte 120,  2, 0, 0 // Arceus
	.byte  80,  4, 0, 0 // Giratina Origin Form
	.byte 120,  2, 0, 0 // Arceus Fighting Type Form
	.byte 120,  2, 0, 0 // Arceus Flying Type Form
	.byte 120,  2, 0, 0 // Arceus Poison Type Form
	.byte 120,  2, 0, 0 // Arceus Ground Type Form
	.byte 120,  2, 0, 0 // Arceus Rock Type Form
	.byte 120,  2, 0, 0 // Arceus Bug Type Form
	.byte 120,  2, 0, 0 // Arceus Ghost Type Form
	.byte 120,  2, 0, 0 // Arceus Steel Type Form
	.byte 120,  2, 0, 0 // Arceus Mystery Type Form
	.byte 120,  2, 0, 0 // Arceus Fire Type Form
	.byte 120,  2, 0, 0 // Arceus Water Type Form
	.byte 120,  2, 0, 0 // Arceus Grass Type Form
	.byte 120,  2, 0, 0 // Arceus Electric Type Form
	.byte 120,  2, 0, 0 // Arceus Psychic Type Form
	.byte 120,  2, 0, 0 // Arceus Ice Type Form
	.byte 120,  2, 0, 0 // Arceus Dragon Type Form
	.byte 120,  2, 0, 0 // Arceus Dark Type Form
	.byte  54, 10, 0, 0 // EGG
	.byte  86,  9, 0, 0 // UNOWN B
	.byte 103,  6, 0, 0 // UNOWN C
	.byte  86,  8, 0, 0 // UNOWN D
	.byte  86, 10, 0, 0 // UNOWN E
	.byte 102, 10, 0, 0 // UNOWN F
	.byte  87,  5, 0, 0 // UNOWN G
	.byte 102,  8, 0, 0 // UNOWN H
	.byte  55,  7, 0, 0 // UNOWN I
	.byte  70,  9, 0, 0 // UNOWN J
	.byte  87,  7, 0, 0 // UNOWN K
	.byte  70, 10, 0, 0 // UNOWN L
	.byte 101, 13, 0, 0 // UNOWN M
	.byte 101, 13, 0, 0 // UNOWN N
	.byte 102,  8, 0, 0 // UNOWN O
	.byte  70, 10, 0, 0 // UNOWN P
	.byte  85, 15, 0, 0 // UNOWN Q
	.byte  69, 12, 0, 0 // UNOWN R
	.byte  87,  4, 0, 0 // UNOWN S
	.byte  69, 13, 0, 0 // UNOWN T
	.byte 101, 13, 0, 0 // UNOWN U
	.byte  86, 11, 0, 0 // UNOWN V
	.byte  85, 13, 0, 0 // UNOWN W
	.byte  85, 15, 0, 0 // UNOWN X
	.byte  70, 10, 0, 0 // UNOWN Y
	.byte  70, 10, 0, 0 // UNOWN Z
	.byte  55,  6, 0, 0 // UNOWN EXCLAMATION
	.byte  71,  6, 0, 0 // UNOWN QUESTION
