	.align 2
gMonFrontPicCoords:: @ 81E7C74
	.byte 136,  0, 0, 0 // Question Mark
	.byte  69, 14, 0, 0 // Bulbasaur
	.byte  86, 10, 0, 0 // Ivysaur
	.byte 136,  3, 0, 0 // Venusaur
	.byte  85, 12, 0, 0 // Charmander
	.byte 102,  6, 0, 0 // Charmeleon
	.byte 136,  1, 0, 0 // Charizard
	.byte 101, 13, 0, 0 // Squirtle
	.byte 102,  8, 0, 0 // Wartortle
	.byte 136,  0, 0, 0 // Blastoise
	.byte  69, 12, 0, 0 // Caterpie
	.byte  84, 12, 0, 0 // Metapod
	.byte 118,  6, 0, 0 // Butterfree
	.byte  84, 12, 0, 0 // Weedle
	.byte  69, 10, 0, 0 // Kakuna
	.byte 134,  6, 0, 0 // Beedrill
	.byte 101, 10, 0, 0 // Pidgey
	.byte 103,  4, 0, 0 // Pidgeotto
	.byte 136,  2, 0, 0 // Pidgeot
	.byte  68, 16, 0, 0 // Rattata
	.byte 102, 11, 0, 0 // Raticate
	.byte  69, 15, 0, 0 // Spearow
	.byte 120,  0, 0, 0 // Fearow
	.byte 101, 12, 0, 0 // Ekans
	.byte 136,  2, 0, 0 // Arbok
	.byte 103,  9, 0, 0 // Pikachu
	.byte 103,  4, 0, 0 // Raichu
	.byte  85, 14, 0, 0 // Sandshrew
	.byte 118,  9, 0, 0 // Sandslash
	.byte  69, 15, 0, 0 // Nidoran(F)
	.byte 102, 11, 0, 0 // Nidorina
	.byte 120,  3, 0, 0 // Nidoqueen
	.byte  85, 12, 0, 0 // Nidoran(M)
	.byte 102,  9, 0, 0 // Nidorino
	.byte 120,  2, 0, 0 // Nidoking
	.byte  85, 16, 0, 0
	.byte 102,  8, 0, 0
	.byte 101, 12, 0, 0
	.byte 136,  3, 0, 0
	.byte  69, 16, 0, 0
	.byte 103,  8, 0, 0
	.byte 103,  6, 0, 0
	.byte 136,  3, 0, 0
	.byte  69, 15, 0, 0
	.byte 102, 10, 0, 0
	.byte 119,  6, 0, 0
	.byte  85, 15, 0, 0
	.byte 134,  8, 0, 0
	.byte 102,  8, 0, 0
	.byte 136,  2, 0, 0
	.byte  84, 18, 0, 0
	.byte 117, 13, 0, 0
	.byte  85, 12, 0, 0
	.byte 119,  7, 0, 0
	.byte  86,  9, 0, 0
	.byte 120,  2, 0, 0
	.byte 101, 14, 0, 0
	.byte 119,  7, 0, 0
	.byte 102, 11, 0, 0
	.byte 136,  2, 0, 0
	.byte 116, 19, 0, 0
	.byte 118, 10, 0, 0
	.byte 118,  8, 0, 0
	.byte 102, 11, 0, 0
	.byte 119,  5, 0, 0
	.byte 135,  4, 0, 0
	.byte  86, 11, 0, 0
	.byte 103,  6, 0, 0
	.byte 136,  1, 0, 0
	.byte 101, 15, 0, 0
	.byte 102, 11, 0, 0
	.byte 119,  5, 0, 0
	.byte  70,  9, 0, 0
	.byte 135,  4, 0, 0
	.byte  84, 18, 0, 0
	.byte 135,  4, 0, 0
	.byte 119,  5, 0, 0
	.byte 102,  8, 0, 0
	.byte 136,  1, 0, 0
	.byte 102, 11, 0, 0
	.byte 134,  8, 0, 0
	.byte  67, 21, 0, 0
	.byte 118,  8, 0, 0
	.byte 102,  9, 0, 0
	.byte  87,  5, 0, 0
	.byte 136,  0, 0, 0
	.byte 118, 10, 0, 0
	.byte 135,  7, 0, 0
	.byte 101, 12, 0, 0
	.byte 135,  4, 0, 0
	.byte  85, 16, 0, 0
	.byte 135,  5, 0, 0
	.byte 119,  6, 0, 0
	.byte 119,  5, 0, 0
	.byte 119,  5, 0, 0
	.byte 120,  2, 0, 0
	.byte 119,  7, 0, 0
	.byte 119,  4, 0, 0
	.byte 101, 13, 0, 0
	.byte 136,  3, 0, 0
	.byte  68, 19, 0, 0
	.byte  85, 14, 0, 0
	.byte 135,  7, 0, 0
	.byte 136,  0, 0, 0
	.byte  85, 15, 0, 0
	.byte 118, 11, 0, 0
	.byte 135,  4, 0, 0
	.byte 103,  4, 0, 0
	.byte 134,  8, 0, 0
	.byte 102,  8, 0, 0
	.byte 136,  2, 0, 0
	.byte 118,  9, 0, 0
	.byte 136,  2, 0, 0
	.byte 118,  9, 0, 0
	.byte 103,  7, 0, 0
	.byte 136,  0, 0, 0
	.byte  69, 15, 0, 0
	.byte 103,  7, 0, 0
	.byte 102, 10, 0, 0
	.byte 119,  4, 0, 0
	.byte 102, 10, 0, 0
	.byte 119,  6, 0, 0
	.byte 102,  8, 0, 0
	.byte 136,  0, 0, 0
	.byte 119,  4, 0, 0
	.byte 120,  2, 0, 0
	.byte 119,  4, 0, 0
	.byte 119,  4, 0, 0
	.byte 120,  0, 0, 0
	.byte 103,  6, 0, 0
	.byte 136,  8, 0, 0
	.byte 133, 13, 0, 0
	.byte  84, 17, 0, 0
	.byte  86,  9, 0, 0
	.byte 103,  6, 0, 0
	.byte 118,  9, 0, 0
	.byte 102, 10, 0, 0
	.byte  85, 13, 0, 0
	.byte  69, 15, 0, 0
	.byte 103,  7, 0, 0
	.byte  84, 17, 0, 0
	.byte 136,  3, 0, 0
	.byte 136,  1, 0, 0
	.byte 135,  5, 0, 0
	.byte 136,  3, 0, 0
	.byte 135,  4, 0, 0
	.byte 136,  0, 0, 0
	.byte 117, 14, 0, 0
	.byte 135,  6, 0, 0
	.byte 136,  0, 0, 0
	.byte 136,  0, 0, 0
	.byte  85, 13, 0, 0
	.byte 117, 13, 0, 0
	.byte 119,  4, 0, 0
	.byte 136,  0, 0, 0
	.byte  85, 14, 0, 0
	.byte 118,  8, 0, 0
	.byte 120,  0, 0, 0
	.byte  85, 15, 0, 0
	.byte 103,  6, 0, 0
	.byte 136,  0, 0, 0
	.byte  71,  4, 0, 0
	.byte 103,  7, 0, 0
	.byte  85, 13, 0, 0
	.byte  88,  3, 0, 0
	.byte  86, 12, 0, 0
	.byte 103,  4, 0, 0
	.byte  84, 19, 0, 0
	.byte 135,  5, 0, 0
	.byte 136,  0, 0, 0
	.byte 117, 16, 0, 0
	.byte 135, 11, 0, 0
	.byte  69, 12, 0, 0
	.byte  68, 20, 0, 0
	.byte  68, 18, 0, 0
	.byte  52, 20, 0, 0
	.byte  70,  9, 0, 0
	.byte  68, 20, 0, 0
	.byte  71,  7, 0, 0
	.byte  85, 16, 0, 0
	.byte  86, 10, 0, 0
	.byte 119,  5, 0, 0
	.byte  69, 14, 0, 0
	.byte 101, 14, 0, 0
	.byte 118,  9, 0, 0
	.byte 103,  6, 0, 0
	.byte 103,  6, 0, 0
	.byte 102, 10, 0, 0
	.byte  85, 15, 0, 0
	.byte 119,  7, 0, 0
	.byte  88,  3, 0, 0
	.byte  68, 16, 0, 0
	.byte  86,  8, 0, 0
	.byte 134, 10, 0, 0
	.byte  84, 16, 0, 0
	.byte 119,  7, 0, 0
	.byte 102,  8, 0, 0
	.byte 103,  8, 0, 0
	.byte 102, 11, 0, 0
	.byte  88,  1, 0, 0
	.byte  85, 12, 0, 0
	.byte  53, 15, 0, 0
	.byte 119,  6, 0, 0
	.byte 136,  3, 0, 0
	.byte  86, 10, 0, 0
	.byte 118,  9, 0, 0
	.byte 116, 17, 0, 0
	.byte 120,  3, 0, 0
	.byte 136,  0, 0, 0
	.byte  85, 13, 0, 0
	.byte  87,  6, 0, 0
	.byte  86, 10, 0, 0
	.byte 136,  0, 0, 0
	.byte 102,  9, 0, 0
	.byte 136,  3, 0, 0
	.byte 103,  5, 0, 0
	.byte  69, 13, 0, 0
	.byte 120,  1, 0, 0
	.byte  69, 13, 0, 0
	.byte  87, 13, 0, 0
	.byte  67, 20, 0, 0
	.byte 102,  8, 0, 0
	.byte 101, 12, 0, 0
	.byte  85, 14, 0, 0
	.byte 102, 10, 0, 0
	.byte  86,  8, 0, 0
	.byte 136,  1, 0, 0
	.byte 136,  0, 0, 0
	.byte  86, 11, 0, 0
	.byte 119,  5, 0, 0
	.byte 120,  4, 0, 0
	.byte  84, 16, 0, 0
	.byte 134,  8, 0, 0
	.byte  85, 15, 0, 0
	.byte 136,  0, 0, 0
	.byte 119,  6, 0, 0
	.byte  70,  9, 0, 0
	.byte 103,  5, 0, 0
	.byte  53, 15, 0, 0
	.byte 118, 10, 0, 0
	.byte  69, 13, 0, 0
	.byte 119,  4, 0, 0
	.byte 119,  6, 0, 0
	.byte 136,  0, 0, 0
	.byte 136,  0, 0, 0
	.byte 136,  0, 0, 0
	.byte  70,  9, 0, 0
	.byte  86,  9, 0, 0
	.byte 136,  0, 0, 0
	.byte 136,  0, 0, 0
	.byte 136,  0, 0, 0
	.byte  85, 14, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 135,  4, 0, 0
	.byte 102,  8, 0, 0
	.byte 135,  4, 0, 0
	.byte 136,  0, 0, 0
	.byte  86,  8, 0, 0
	.byte 136,  1, 0, 0
	.byte 136,  0, 0, 0
	.byte  86, 12, 0, 0
	.byte 103,  6, 0, 0
	.byte 136,  0, 0, 0
	.byte  85, 12, 0, 0
	.byte 135,  4, 0, 0
	.byte 133, 15, 0, 0
	.byte 120,  3, 0, 0
	.byte  69, 14, 0, 0
	.byte 117, 17, 0, 0
	.byte 134,  9, 0, 0
	.byte 116, 16, 0, 0
	.byte 134, 15, 0, 0
	.byte 101, 14, 0, 0
	.byte 102,  9, 0, 0
	.byte 136,  0, 0, 0
	.byte  70, 16, 0, 0
	.byte  86,  8, 0, 0
	.byte 136,  2, 0, 0
	.byte 116, 18, 0, 0
	.byte 134, 10, 0, 0
	.byte 102, 10, 0, 0
	.byte 100, 16, 0, 0
	.byte 135,  6, 0, 0
	.byte  84, 16, 0, 0
	.byte 119,  4, 0, 0
	.byte 104,  1, 0, 0
	.byte 132, 24, 0, 0
	.byte 119,  4, 0, 0
	.byte 101, 15, 0, 0
	.byte 136,  1, 0, 0
	.byte 117, 15, 0, 0
	.byte 135, 10, 0, 0
	.byte 102, 11, 0, 0
	.byte 102,  8, 0, 0
	.byte 103,  7, 0, 0
	.byte  85, 16, 0, 0
	.byte 120,  6, 0, 0
	.byte  86, 12, 0, 0
	.byte 136,  2, 0, 0
	.byte 102,  9, 0, 0
	.byte  70, 11, 0, 0
	.byte 118,  9, 0, 0
	.byte  70, 24, 0, 0
	.byte 102, 12, 0, 0
	.byte 136,  1, 0, 0
	.byte  70, 13, 0, 0
	.byte 136,  0, 0, 0
	.byte 103,  6, 0, 0
	.byte 120,  3, 0, 0
	.byte  84, 16, 0, 0
	.byte 134, 12, 0, 0
	.byte 136,  1, 0, 0
	.byte 101, 12, 0, 0
	.byte 136,  1, 0, 0
	.byte 100, 18, 0, 0
	.byte 103,  4, 0, 0
	.byte 101, 15, 0, 0
	.byte 135,  9, 0, 0
	.byte 101, 16, 0, 0
	.byte 134, 10, 0, 0
	.byte 136,  1, 0, 0
	.byte 116, 16, 0, 0
	.byte 136,  0, 0, 0
	.byte  86, 11, 0, 0
	.byte 118, 10, 0, 0
	.byte 102,  9, 0, 0
	.byte 136,  1, 0, 0
	.byte  85, 15, 0, 0
	.byte  70,  9, 0, 0
	.byte 119,  5, 0, 0
	.byte  86, 14, 0, 0
	.byte 102, 12, 0, 0
	.byte 118,  8, 0, 0
	.byte 101, 12, 0, 0
	.byte 104,  1, 0, 0
	.byte 118, 17, 0, 0
	.byte 136,  2, 0, 0
	.byte  85, 12, 0, 0
	.byte 102, 10, 0, 0
	.byte 119,  5, 0, 0
	.byte 118,  8, 0, 0
	.byte 116, 18, 0, 0
	.byte 120,  0, 0, 0
	.byte 134,  8, 0, 0
	.byte  85, 18, 0, 0
	.byte 102,  8, 0, 0
	.byte 136,  0, 0, 0
	.byte  85, 14, 0, 0
	.byte 120,  3, 0, 0
	.byte 136,  1, 0, 0
	.byte  85, 14, 0, 0
	.byte 120,  3, 0, 0
	.byte 134, 11, 0, 0
	.byte 104,  0, 0, 0
	.byte  86, 14, 0, 0
	.byte  85, 12, 0, 0
	.byte 119,  8, 0, 0
	.byte 135,  5, 0, 0
	.byte 119, 11, 0, 0
	.byte  67, 20, 0, 0
	.byte 117, 13, 0, 0
	.byte 136,  0, 0, 0
	.byte  52, 17, 0, 0
	.byte 102,  8, 0, 0
	.byte  86,  8, 0, 0
	.byte 103,  7, 0, 0
	.byte 120,  0, 0, 0
	.byte 102,  8, 0, 0
	.byte 136,  0, 0, 0
	.byte  53, 15, 0, 0
	.byte  71,  6, 0, 0
	.byte 120,  1, 0, 0
	.byte  86, 11, 0, 0
	.byte 102,  9, 0, 0
	.byte 135,  4, 0, 0
	.byte  85, 15, 0, 0
	.byte 135,  7, 0, 0
	.byte 135,  6, 0, 0
	.byte 120,  4, 0, 0
	.byte 136,  2, 0, 0
	.byte 136,  3, 0, 0
	.byte 135,  4, 0, 0
	.byte 136,  1, 0, 0
	.byte 136,  0, 0, 0
	.byte 136,  1, 0, 0
	.byte 136,  2, 0, 0
	.byte 102, 13, 0, 0
	.byte 136,  1, 0, 0
	.byte  55,  6, 0, 0 // Chimecho
	.byte 136, 14, 0, 0 // Turtwig
	.byte  86, 10, 0, 0 // Grotle
	.byte 136,  3, 0, 0 // Torterra
	.byte  85, 12, 0, 0 // Chimchar
	.byte 102,  9, 0, 0 // Monferno
	.byte 136,  1, 0, 0 // Infernape
	.byte 101, 13, 0, 0 // Piplup
	.byte 102,  8, 0, 0 // Prinplup
	.byte 136,  0, 0, 0 // Empoleon
	.byte 101, 13, 0, 0 // Starly
	.byte 103, 11, 0, 0 // Staravia
	.byte 136,  1, 0, 0 // Staraptor
	.byte 101, 13, 0, 0 // Bidoof
	.byte 102,  9, 0, 0 // Bibarel
	.byte 103, 11, 0, 0 // Kricketot
	.byte 102,  9, 0, 0 // Kricketune
	.byte  85, 12, 0, 0 // Shinx
	.byte 102,  9, 0, 0 // Luxio
	.byte 120,  6, 0, 0 // Luxray
	.byte 103,  9, 0, 0 // Budew
	.byte 103,  4, 0, 0 // Roserade
	.byte 103,  9, 0, 0 // Cranidos
	.byte 103,  4, 0, 0 // Rampardos
	.byte  85, 14, 0, 0 // Shieldon
	.byte 118,  9, 0, 0 // Bastiodon
	.byte  84,  4, 0, 0 // Burmy
	.byte  84,  4, 0, 0 // Wormadam
	.byte 120,  0, 0, 0 // Mothim
	.byte  69,  9, 0, 0 // Combee
	.byte 134,  4, 0, 0 // Vespiquen
	.byte 103,  9, 0, 0 // Pachirisu
	.byte 101, 12, 0, 0 // Buizel
	.byte 136,  2, 0, 0 // Floatzel
	.byte  69, 16, 0, 0 // Cherubi
	.byte  84,  8, 0, 0 // Cherrim
	.byte 101, 12, 0, 0 // Shellos (East)
	.byte 136,  2, 0, 0 // Gastrodon (East)
	.byte  84,  1, 0, 0 // Ambipom
	.byte  84,  4, 0, 0 // Drifloon
	.byte 120,  0, 0, 0 // Drifblim
	.byte 136,  3, 0, 0 // Buneary
	.byte 136,  3, 0, 0 // Lopunny
	.byte 134,  4, 0, 0 // Mismagius
	.byte 136,  5, 0, 0 // Honchkrow
	.byte  85,  9, 0, 0 // Glameow
	.byte 102,  6, 0, 0 // Purugly
	.byte 103, 11, 0, 0 // Chingling
	.byte  85,  9, 0, 0 // Stunky
	.byte 102,  6, 0, 0 // Skuntank
	.byte  84,  4, 0, 0 // Bronzor
	.byte  84,  4, 0, 0 // Bronzong
	.byte 101,  8, 0, 0 // Bonsly
	.byte   0,  8, 0, 0 // Mime Jr.
	.byte 101,  8, 0, 0 // Happiny
	.byte 101, 10, 0, 0 // Chatot
	.byte  84,  4, 0, 0 // Spiritomb
	.byte  85, 12, 0, 0 // Gible
	.byte  85,  4, 0, 0 // Gabite
	.byte 136,  1, 0, 0 // Garchomp
	.byte 101, 10, 0, 0 // Munchlax
	.byte 103, 11, 0, 0 // Riolu
	.byte  85,  3, 0, 0 // Lucario
	.byte 102,  8, 0, 0 // Hippopotas
	.byte 136,  9, 0, 0 // Hippowdon
	.byte 102,  9, 0, 0 // Skorupi
	.byte 120,  6, 0, 0 // Drapion
	.byte  85,  8, 0, 0 // Croagunk
	.byte 102,  6, 0, 0 // Toxicroak
	.byte 102, 10, 0, 0 // Carnivine
	.byte 101, 13, 0, 0 // Finneon
	.byte 102,  6, 0, 0 // Lumineon
	.byte 101, 13, 0, 0 // Mantyke
	.byte 103, 11, 0, 0 // Snover
	.byte 136,  1, 0, 0 // Abomasnow
	.byte  85,  4, 0, 0 // Weavile
	.byte  84,  4, 0, 0 // Magnezone
	.byte 102,  3, 0, 0 // Lickilicky
	.byte 136,  4, 0, 0 // Rhyperior
	.byte 102,  3, 0, 0 // Tangrowth
	.byte 102,  3, 0, 0 // Electivire
	.byte 102,  3, 0, 0 // Magmortar
	.byte  84,  1, 0, 0 // Togekiss
	.byte  84,  1, 0, 0 // Yanmega
	.byte 102,  9, 0, 0 // Leafeon
	.byte 102,  9, 0, 0 // Glaceon
	.byte  84,  1, 0, 0 // Gliscor
	.byte 136,  4, 0, 0 // Mamoswine
	.byte 136,  4, 0, 0 // Porygon-Z
	.byte 102,  1, 0, 0 // Gallade
	.byte 102,  2, 0, 0 // Probopass
	.byte 136,  1, 0, 0 // Dusknoir
	.byte  85,  4, 0, 0 // Froslass
	.byte  84,  1, 0, 0 // Rotom
	.byte 132,  2, 0, 0 // Uxie
	.byte 136,  0, 0, 0 // Mesprit
	.byte 136,  1, 0, 0 // Azelf
	.byte 136,  1, 0, 0 // Dialga
	.byte 136,  1, 0, 0 // Palkia
	.byte 102,  9, 0, 0 // Heatran
	.byte 136,  1, 0, 0 // Regigigas
	.byte 136,  1, 0, 0 // Giratina
	.byte 136,  0, 0, 0 // Cresselia
	.byte 102, 11, 0, 0 // Phione
	.byte 102, 11, 0, 0 // Manaphy
	.byte 136,  0, 0, 0 // Darkrai
	.byte  85, 12, 0, 0 // Shaymin
	.byte 136,  1, 0, 0 // Arceus
	.byte 136,  4, 0, 0 // Giratina (Origin Form)
	.byte  51, 20, 0, 0 // EGG
	.byte  52, 16, 0, 0 // UNOWN B
	.byte  68, 16, 0, 0 // UNOWN C
	.byte  68, 16, 0, 0 // UNOWN D
	.byte  68, 17, 0, 0 // UNOWN E
	.byte  68, 17, 0, 0 // UNOWN F
	.byte  53, 14, 0, 0 // UNOWN G
	.byte  68, 16, 0, 0 // UNOWN H
	.byte  52, 16, 0, 0 // UNOWN I
	.byte  52, 17, 0, 0 // UNOWN J
	.byte  68, 17, 0, 0 // UNOWN K
	.byte  52, 19, 0, 0 // UNOWN L
	.byte  68, 19, 0, 0 // UNOWN M
	.byte  67, 20, 0, 0 // UNOWN N
	.byte  68, 16, 0, 0 // UNOWN O
	.byte  52, 19, 0, 0 // UNOWN P
	.byte  67, 21, 0, 0 // UNOWN Q
	.byte  52, 19, 0, 0 // UNOWN R
	.byte  69, 12, 0, 0 // UNOWN S
	.byte  52, 18, 0, 0 // UNOWN T
	.byte  68, 18, 0, 0 // UNOWN U
	.byte  68, 18, 0, 0 // UNOWN V
	.byte  68, 19, 0, 0 // UNOWN W
	.byte  51, 21, 0, 0 // UNOWN X
	.byte  52, 17, 0, 0 // UNOWN Y
	.byte  52, 16, 0, 0 // UNOWN Z
	.byte  53, 15, 0, 0 // UNOWN EXCLAMATION
	.byte  53, 13, 0, 0 // UNOWN QUESTION
